---
# Configuration yamllint pour les manifestes Kubernetes
# Documentation : https://yamllint.readthedocs.io/

extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start:
    present: false
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: true
